"""product image

Revision ID: a519c21bdf8b
Revises: f1cc368fd917
Create Date: 2021-06-14 13:07:16.796746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a519c21bdf8b'
down_revision = 'f1cc368fd917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
