"""file upload

Revision ID: f1cc368fd917
Revises: e21d8a8f2dac
Create Date: 2021-06-13 13:14:55.867772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1cc368fd917'
down_revision = 'e21d8a8f2dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('path', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'path')
    # ### end Alembic commands ###
